services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/mydb
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    # volumes:
    #   - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres-init:
    build:
      context: .
      dockerfile: docker/Dockerfile.init
    command: ["/app/postgres-init.sh"]
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/mydb
    restart: "no"

  redis-init:
    build:
      context: .
      dockerfile: docker/Dockerfile.init
    working_dir: /app/packages/store
    command: >
        sh -c "/app/wait-for-redis.sh redis 6379 && bun run redis-seed"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_URL: "redis://redis:6379"
    restart: "no"
    
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/mydb
      REDIS_URL: redis://redis:6379
      JWT_SECRET: secret
      PORT: 3001
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      redis-init:
        condition: service_completed_successfully
      postgres-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:3001
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped

  pusher:
    build:
      context: .
      dockerfile: docker/Dockerfile.pusher
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/mydb
      REDIS_URL: redis://redis:6379
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      api:
        condition: service_started
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/mydb
      REDIS_URL: redis://redis:6379
      REGION_ID: f5a13f6c-8e91-42b8-9c0e-07b4567a98e0
      WORKER_ID: "1"
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      api:
        condition: service_started
    restart: unless-stopped

# volumes:
#   postgres_data:
#   redis_data: