# Global configuration
global:
  imageRegistry: ""
  imagePullSecrets: []

# Application configuration
app:
  name: upguard
  version: "1.0.0"

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    postgresPassword: postgres
    username: postgres
    password: postgres
    database: mydb
  primary:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m

# Redis configuration
redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m

# API service configuration
api:
  replicaCount: 1
  image:
    repository: upguard/api
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3001
    targetPort: 3001
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
  env:
    JWT_SECRET: secret
    PORT: "3001"
  healthCheck:
    enabled: true
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 10

# Frontend service configuration
frontend:
  replicaCount: 1
  image:
    repository: upguard/frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80
    targetPort: 3000
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  env:
    PORT: "3000"

# Pusher service configuration
pusher:
  replicaCount: 1
  image:
    repository: upguard/pusher
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

# Worker service configuration
worker:
  replicaCount: 2
  image:
    repository: upguard/worker
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  env:
    REGION_ID: f5a13f6c-8e91-42b8-9c0e-07b4567a98e0

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: upguard.local
      paths:
        - path: /
          pathType: Prefix
          service: frontend
        - path: /api
          pathType: Prefix
          service: api
  tls: []

# Init jobs configuration
initJobs:
  enabled: true
  postgres:
    image:
      repository: upguard/init
      tag: latest
      pullPolicy: IfNotPresent
  redis:
    image:
      repository: upguard/init
      tag: latest
      pullPolicy: IfNotPresent